clc
clear
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Checks the body-frame vectors generated by Sensor Model and
% Star-Matching

% Result -> The Body-Frame vectors match!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Input
% Folder - Feature Extraction Input
file_base_ip = '.\Star_Matching\4_Star_Matching\MILS\Expected_Input\Simulation_3\Image_';
file_base_op = '.\Star_Matching\4_Star_Matching\MILS\ST_Testing\Body_Frame_Vectors\';
PIXEL_WIDTH = 4.8e-3;
Focal_Length = 25;


%% Check Body-frame vectors
data_mean = zeros(15,2);
tic
for i = 1:15
    %% Input
    file_loc_ip = strcat(file_base_ip , num2str(i) , '\se_Table_' ,  num2str(i) , '.mat');
    load(file_loc_ip);
    file_loc_ip = strcat(file_base_ip , num2str(i) , '\se_Verification_' ,  num2str(i) , '.mat');
    load(file_loc_ip);

    %% Expected Body-frame vectors
    st_bi_exp = [se_T_Final.SSP_ID, se_T_Final.r3];
    sz = size(st_bi_exp);
    fe_n_str = sz(1);
    clear sz
    
    %% Actual Body-frame vectors
    fe_output = [se_T_Verification.SSP_ID, se_T_Verification.Sensor_X*PIXEL_WIDTH, se_T_Verification.Sensor_Y*PIXEL_WIDTH];
    st_bi_act = st_gnrt_bi(fe_output, fe_n_str, Focal_Length);   
   
    
    %% Check Angular Distance
    N = fe_n_str;
    % Create matrices to store data
    data_mat = zeros(N*(N-1)*0.5, 5);
    
    % Store Data
    kidx = 1;
    for idx = 1:N-1
        for jdx = (idx+1):N            
            c1 = st_bi_exp(idx, 1);
            c2 = st_bi_exp(jdx, 1);
            
            bi_idx_exp = st_bi_exp(idx, 2:4);
            bi_jdx_exp = st_bi_exp(jdx, 2:4);
            c3 = dot(bi_idx_exp, bi_jdx_exp);

            bi_idx_act = st_bi_act(idx, 2:4);
            bi_jdx_act = st_bi_act(jdx, 2:4);
            c4 = dot(bi_idx_act, bi_jdx_act);
            
            c5 = abs(1 - c3/c4)*100;
            
            data_mat(kidx, :) = [c1, c2, c3, c4, c5]; 
            kidx = kidx + 1;
        end        
    end
    data_table = array2table(data_mat, 'VariableNames', {'SSP_ID1', 'SSP_ID2', 'AngDst_Exp', 'AngDst_Act', 'ErrorPercent'});
    mean_err = mean(data_table.ErrorPercent);   
    
    %% Write Output    
    file_loc_op = strcat(file_base_op , 'st_output_' , num2str(i) , '.mat');
    save(file_loc_op, 'data_table', 'mean_err');        
    
    data_mean(i,:) = [i, mean_err];
end
toc
file_loc_op = strcat(file_base_op , 'st_summary_body_frame_vectors.mat');
save(file_loc_op, 'data_mean');  